server {
    listen 8080;
    server_name _;

    # Nén Gzip để tải trang nhanh hơn
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Hỗ trợ React Router (nếu có sử dụng các route nội bộ)
        try_files $uri $uri/ /index.html;
    }

    # Cache các file tĩnh (CSS, JS, Hình ảnh)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
